"""initial migration

Revision ID: 555da135dce7
Revises: 
Create Date: 2026-08-04 20:37:22.787385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '555da135dce7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_skills_ibfk_2'), 'job_skills', type_='foreignkey')
    op.drop_constraint(op.f('job_skills_ibfk_1'), 'job_skills', type_='foreignkey')
    op.create_foreign_key(None, 'job_skills', 'skills', ['skill_id'], ['id'])
    op.create_foreign_key(None, 'job_skills', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.drop_constraint(None, 'job_skills', type_='foreignkey')
    op.create_foreign_key(op.f('job_skills_ibfk_1'), 'job_skills', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('job_skills_ibfk_2'), 'job_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
